# Generated by Django 3.0.5 on 2021-02-10 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Testresult_WP3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=50)),
                ('image_quid', models.IntegerField(default=0)),
                ('anomaly', models.CharField(default='', max_length=16)),
                ('image_one', models.FileField(upload_to='image_one')),
                ('image_one_net', models.CharField(choices=[('Xception', 'Xception'), ('ResNet', 'ResNet'), ('DenseNet', 'DenseNet'), ('EfficientNet', 'EfficientNet')], max_length=16)),
                ('image_two', models.FileField(upload_to='image_two')),
                ('image_two_net', models.CharField(choices=[('Xception', 'Xception'), ('ResNet', 'ResNet'), ('DenseNet', 'DenseNet'), ('EfficientNet', 'EfficientNet')], max_length=16)),
                ('image_three', models.FileField(upload_to='image_three')),
                ('image_three_net', models.CharField(choices=[('Xception', 'Xception'), ('ResNet', 'ResNet'), ('DenseNet', 'DenseNet'), ('EfficientNet', 'EfficientNet')], max_length=16)),
                ('image_four', models.FileField(upload_to='image_four')),
                ('image_four_net', models.CharField(choices=[('Xception', 'Xception'), ('ResNet', 'ResNet'), ('DenseNet', 'DenseNet'), ('EfficientNet', 'EfficientNet')], max_length=16)),
                ('image_one_score', models.IntegerField(default=0)),
                ('image_two_score', models.IntegerField(default=0)),
                ('image_three_score', models.IntegerField(default=0)),
                ('image_four_score', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='UserProgress_WP3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('progress', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='WP3_Questions',
            fields=[
                ('q_id', models.IntegerField(primary_key=True, serialize=False)),
                ('anomaly', models.CharField(default='', max_length=16)),
                ('original_image', models.FileField(upload_to='image_one')),
                ('image_one', models.FileField(upload_to='image_one')),
                ('image_one_net', models.CharField(choices=[('Xception', 'Xception'), ('ResNet', 'ResNet'), ('DenseNet', 'DenseNet'), ('EfficientNet', 'EfficientNet')], max_length=16)),
                ('image_two', models.FileField(upload_to='image_two')),
                ('image_two_net', models.CharField(choices=[('Xception', 'Xception'), ('ResNet', 'ResNet'), ('DenseNet', 'DenseNet'), ('EfficientNet', 'EfficientNet')], max_length=16)),
                ('image_three', models.FileField(upload_to='image_three')),
                ('image_three_net', models.CharField(choices=[('Xception', 'Xception'), ('ResNet', 'ResNet'), ('DenseNet', 'DenseNet'), ('EfficientNet', 'EfficientNet')], max_length=16)),
                ('image_four', models.FileField(upload_to='image_four')),
                ('image_four_net', models.CharField(choices=[('Xception', 'Xception'), ('ResNet', 'ResNet'), ('DenseNet', 'DenseNet'), ('EfficientNet', 'EfficientNet')], max_length=16)),
            ],
        ),
    ]
