# Generated by Django 3.0.5 on 2020-12-03 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WP3', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testresult_wp3',
            name='image_four_net',
            field=models.CharField(choices=[('Xception', 'Xception'), ('ResNet', 'ResNet'), ('DenseNet', 'DenseNet'), ('EfficientNet', 'EfficientNet')], max_length=16),
        ),
        migrations.AlterField(
            model_name='testresult_wp3',
            name='image_one_net',
            field=models.CharField(choices=[('Xception', 'Xception'), ('ResNet', 'ResNet'), ('DenseNet', 'DenseNet'), ('EfficientNet', 'EfficientNet')], max_length=16),
        ),
        migrations.AlterField(
            model_name='testresult_wp3',
            name='image_three_net',
            field=models.CharField(choices=[('Xception', 'Xception'), ('ResNet', 'ResNet'), ('DenseNet', 'DenseNet'), ('EfficientNet', 'EfficientNet')], max_length=16),
        ),
        migrations.AlterField(
            model_name='testresult_wp3',
            name='image_two_net',
            field=models.CharField(choices=[('Xception', 'Xception'), ('ResNet', 'ResNet'), ('DenseNet', 'DenseNet'), ('EfficientNet', 'EfficientNet')], max_length=16),
        ),
        migrations.AlterField(
            model_name='wp3_questions',
            name='image_four_net',
            field=models.CharField(choices=[('Xception', 'Xception'), ('ResNet', 'ResNet'), ('DenseNet', 'DenseNet'), ('EfficientNet', 'EfficientNet')], max_length=16),
        ),
        migrations.AlterField(
            model_name='wp3_questions',
            name='image_one_net',
            field=models.CharField(choices=[('Xception', 'Xception'), ('ResNet', 'ResNet'), ('DenseNet', 'DenseNet'), ('EfficientNet', 'EfficientNet')], max_length=16),
        ),
        migrations.AlterField(
            model_name='wp3_questions',
            name='image_three_net',
            field=models.CharField(choices=[('Xception', 'Xception'), ('ResNet', 'ResNet'), ('DenseNet', 'DenseNet'), ('EfficientNet', 'EfficientNet')], max_length=16),
        ),
        migrations.AlterField(
            model_name='wp3_questions',
            name='image_two_net',
            field=models.CharField(choices=[('Xception', 'Xception'), ('ResNet', 'ResNet'), ('DenseNet', 'DenseNet'), ('EfficientNet', 'EfficientNet')], max_length=16),
        ),
    ]
