# Generated by Django 3.0.5 on 2020-12-04 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WP3', '0002_auto_20201203_2241'),
    ]

    operations = [
        migrations.AddField(
            model_name='testresult_wp3',
            name='anomaly',
            field=models.CharField(default='', max_length=16),
        ),
        migrations.AddField(
            model_name='wp3_questions',
            name='anomaly',
            field=models.CharField(default='', max_length=16),
        ),
    ]
