# Generated by Django 3.0.3 on 2020-03-04 10:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image_tb',
            fields=[
                ('q_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('modality', models.CharField(max_length=50)),
                ('dataset', models.CharField(max_length=50)),
                ('real_image', models.FileField(upload_to='realimage')),
                ('fake_image', models.FileField(upload_to='fakeimage')),
            ],
        ),
    ]
