# Generated by Django 3.0.3 on 2020-03-05 07:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('vttapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CT',
            fields=[
                ('q_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('dataset', models.CharField(max_length=50)),
                ('real_image', models.FileField(upload_to='realimage')),
                ('fake_image', models.FileField(upload_to='fakeimage')),
            ],
        ),
        migrations.CreateModel(
            name='MR',
            fields=[
                ('q_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('dataset', models.CharField(max_length=50)),
                ('real_image', models.FileField(upload_to='realimage')),
                ('fake_image', models.FileField(upload_to='fakeimage')),
            ],
        ),
        migrations.CreateModel(
            name='XR',
            fields=[
                ('q_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('dataset', models.CharField(max_length=50)),
                ('real_image', models.FileField(upload_to='realimage')),
                ('fake_image', models.FileField(upload_to='fakeimage')),
            ],
        ),
        migrations.DeleteModel(
            name='Image_tb',
        ),
    ]
