# Generated by Django 3.0.4 on 2020-03-10 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vttapp', '0003_auto_20200310_0009'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testresult',
            fields=[
                ('s_id', models.UUIDField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50)),
                ('dataset', models.CharField(max_length=50)),
                ('selcted_image', models.CharField(max_length=50)),
                ('confidence', models.IntegerField()),
            ],
        ),
    ]
