# Generated by Django 3.0.4 on 2020-03-11 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vttapp', '0007_userprogress'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprogress',
            old_name='progress',
            new_name='ct_progress',
        ),
        migrations.AddField(
            model_name='userprogress',
            name='mr_progress',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprogress',
            name='xr_progress',
            field=models.IntegerField(default=0),
        ),
    ]
