# Generated by Django 3.0.4 on 2020-03-16 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vttapp', '0008_auto_20200311_1533'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResponseSheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataset', models.CharField(max_length=50)),
                ('total_pass', models.IntegerField(default=0)),
                ('total_fail', models.IntegerField(default=0)),
                ('avg_confidence', models.IntegerField(default=0)),
            ],
        ),
    ]
