# Generated by Django 3.0.5 on 2020-10-04 18:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('vttapp', '0009_responsesheet'),
    ]

    operations = [
        migrations.AddField(
            model_name='ct',
            name='original_image',
            field=models.FileField(default=django.utils.timezone.now, upload_to='originalimage'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mr',
            name='original_image',
            field=models.FileField(default=django.utils.timezone.now, upload_to='originalimage'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='xr',
            name='original_image',
            field=models.FileField(default=0, upload_to='originalimage'),
            preserve_default=False,
        ),
    ]
