# Generated by Django 3.0.5 on 2020-10-07 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vttapp', '0011_auto_20201005_0000'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='xr',
            name='our_image',
        ),
        migrations.AddField(
            model_name='xr',
            name='miriad_image',
            field=models.FileField(default=0, upload_to='miriadimage'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ct',
            name='jpeg_image',
            field=models.FileField(upload_to='jpegimage'),
        ),
        migrations.AlterField(
            model_name='ct',
            name='our_image',
            field=models.FileField(upload_to='miriadimage'),
        ),
        migrations.AlterField(
            model_name='mr',
            name='jpeg_image',
            field=models.FileField(upload_to='jpegimage'),
        ),
        migrations.AlterField(
            model_name='mr',
            name='our_image',
            field=models.FileField(upload_to='miriadimage'),
        ),
        migrations.AlterField(
            model_name='xr',
            name='jpeg_image',
            field=models.FileField(upload_to='jpegimage'),
        ),
    ]
