# Generated by Django 3.0.5 on 2020-10-07 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vttapp', '0012_auto_20201007_2127'),
    ]

    operations = [
        migrations.AddField(
            model_name='responsesheet',
            name='total_fail2',
            field=models.IntegerField(default=0),
        ),
    ]
