# Generated by Django 3.0.5 on 2020-10-07 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vttapp', '0013_responsesheet_total_fail2'),
    ]

    operations = [
        migrations.AddField(
            model_name='responsesheet',
            name='option3_count',
            field=models.IntegerField(default=0),
        ),
    ]
