# Generated by Django 3.0.5 on 2020-10-08 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vttapp', '0014_responsesheet_option3_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ct',
            old_name='our_image',
            new_name='miriad_image',
        ),
        migrations.RenameField(
            model_name='mr',
            old_name='our_image',
            new_name='miriad_image',
        ),
    ]
