# Generated by Django 3.0.5 on 2020-10-08 19:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('vttapp', '0015_auto_20201008_2057'),
    ]

    operations = [
        migrations.AddField(
            model_name='ct',
            name='organ',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mr',
            name='organ',
            field=models.CharField(default=23, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='xr',
            name='organ',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
