# Generated by Django 3.0.5 on 2020-10-12 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vttapp', '0017_userrequest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userrequest',
            old_name='registeration_number',
            new_name='registration_number',
        ),
    ]
