# Generated by Django 3.0.5 on 2020-10-14 10:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('vttapp', '0018_auto_20201012_1302'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ct',
            old_name='miriad_image',
            new_name='image_one',
        ),
        migrations.RenameField(
            model_name='ct',
            old_name='jpeg_image',
            new_name='image_two',
        ),
        migrations.RenameField(
            model_name='xr',
            old_name='miriad_image',
            new_name='image_one',
        ),
        migrations.RenameField(
            model_name='xr',
            old_name='jpeg_image',
            new_name='image_two',
        ),
        migrations.RemoveField(
            model_name='mr',
            name='jpeg_image',
        ),
        migrations.RemoveField(
            model_name='mr',
            name='miriad_image',
        ),
        migrations.AddField(
            model_name='mr',
            name='alpha_value',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mr',
            name='beta_value',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mr',
            name='bit_depth',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mr',
            name='compression_factor',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mr',
            name='hauffman_coding',
            field=models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No')], max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='mr',
            name='image_one',
            field=models.FileField(default=django.utils.timezone.now, upload_to='image_one'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mr',
            name='image_one_format',
            field=models.CharField(choices=[('MIRIAD', 'MIRIAD'), ('JPEG', 'JPEG'), ('J2K', 'J2K')], default=django.utils.timezone.now, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mr',
            name='image_two',
            field=models.FileField(default=django.utils.timezone.now, upload_to='image_two'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mr',
            name='image_two_format',
            field=models.CharField(choices=[('MIRIAD', 'MIRIAD'), ('JPEG', 'JPEG'), ('J2K', 'J2K')], default=django.utils.timezone.now, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mr',
            name='quality_factor',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mr',
            name='quantizer_bit_depth',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
