# Generated by Django 3.0.5 on 2020-10-14 10:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('vttapp', '0019_auto_20201014_1557'),
    ]

    operations = [
        migrations.AddField(
            model_name='ct',
            name='alpha_value',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ct',
            name='beta_value',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ct',
            name='bit_depth',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ct',
            name='compression_factor',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ct',
            name='hauffman_coding',
            field=models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No')], max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='ct',
            name='image_one_format',
            field=models.CharField(choices=[('MIRIAD', 'MIRIAD'), ('JPEG', 'JPEG'), ('J2K', 'J2K')], default=django.utils.timezone.now, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ct',
            name='image_two_format',
            field=models.CharField(choices=[('MIRIAD', 'MIRIAD'), ('JPEG', 'JPEG'), ('J2K', 'J2K')], default=django.utils.timezone.now, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ct',
            name='quality_factor',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ct',
            name='quantizer_bit_depth',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='testresult',
            name='image_quid',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='xr',
            name='alpha_value',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='xr',
            name='beta_value',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='xr',
            name='bit_depth',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='xr',
            name='compression_factor',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='xr',
            name='hauffman_coding',
            field=models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No')], max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='xr',
            name='image_one_format',
            field=models.CharField(choices=[('MIRIAD', 'MIRIAD'), ('JPEG', 'JPEG'), ('J2K', 'J2K')], default=django.utils.timezone.now, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='xr',
            name='image_two_format',
            field=models.CharField(choices=[('MIRIAD', 'MIRIAD'), ('JPEG', 'JPEG'), ('J2K', 'J2K')], default=django.utils.timezone.now, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='xr',
            name='quality_factor',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='xr',
            name='quantizer_bit_depth',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ct',
            name='image_one',
            field=models.FileField(upload_to='image_one'),
        ),
        migrations.AlterField(
            model_name='ct',
            name='image_two',
            field=models.FileField(upload_to='image_two'),
        ),
        migrations.AlterField(
            model_name='xr',
            name='image_one',
            field=models.FileField(upload_to='image_one'),
        ),
        migrations.AlterField(
            model_name='xr',
            name='image_two',
            field=models.FileField(upload_to='image_two'),
        ),
    ]
