# Generated by Django 3.0.5 on 2020-10-14 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vttapp', '0020_auto_20201014_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ct',
            name='alpha_value',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ct',
            name='beta_value',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mr',
            name='alpha_value',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mr',
            name='beta_value',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='xr',
            name='alpha_value',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='xr',
            name='beta_value',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
