# Generated by Django 3.0.5 on 2020-10-25 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vttapp', '0021_auto_20201014_1623'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testresult',
            name='image_quid',
        ),
        migrations.RemoveField(
            model_name='testresult',
            name='selcted_image',
        ),
    ]
