# Generated by Django 3.0.5 on 2020-12-03 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vttapp', '0023_auto_20201026_0003'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ResponseSheet',
        ),
        migrations.RemoveField(
            model_name='ct',
            name='compression_factor',
        ),
        migrations.RemoveField(
            model_name='ct',
            name='quality_factor',
        ),
        migrations.RemoveField(
            model_name='mr',
            name='compression_factor',
        ),
        migrations.RemoveField(
            model_name='mr',
            name='quality_factor',
        ),
        migrations.RemoveField(
            model_name='testresult',
            name='compression_factor',
        ),
        migrations.RemoveField(
            model_name='testresult',
            name='quality_factor',
        ),
        migrations.RemoveField(
            model_name='xr',
            name='compression_factor',
        ),
        migrations.RemoveField(
            model_name='xr',
            name='quality_factor',
        ),
        migrations.AddField(
            model_name='ct',
            name='compression_factor_image1',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ct',
            name='compression_factor_image2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mr',
            name='compression_factor_image1',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mr',
            name='compression_factor_image2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='testresult',
            name='compression_factor_image1',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='testresult',
            name='compression_factor_image2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='xr',
            name='compression_factor_image1',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='xr',
            name='compression_factor_image2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ct',
            name='bit_depth',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ct',
            name='quantizer_bit_depth',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mr',
            name='bit_depth',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mr',
            name='quantizer_bit_depth',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='bit_depth',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='quantizer_bit_depth',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='xr',
            name='bit_depth',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='xr',
            name='quantizer_bit_depth',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
