# Generated by Django 3.0.5 on 2021-08-26 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CT_Likter',
            fields=[
                ('q_id', models.IntegerField(primary_key=True, serialize=False)),
                ('dataset', models.CharField(max_length=50)),
                ('organ', models.CharField(max_length=50)),
                ('original_image', models.FileField(upload_to='originalimage')),
                ('image', models.FileField(upload_to='image_one')),
                ('image_format', models.CharField(choices=[('MIRIAD', 'MIRIAD'), ('JPEG', 'JPEG'), ('J2K', 'J2K')], max_length=10)),
                ('alpha_value', models.FloatField(blank=True, null=True)),
                ('beta_value', models.FloatField(blank=True, null=True)),
                ('hauffman_coding', models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No')], max_length=12, null=True)),
                ('bit_depth', models.FloatField(blank=True, null=True)),
                ('quantizer_bit_depth', models.FloatField(blank=True, null=True)),
                ('compression_factor', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MR_Likter',
            fields=[
                ('q_id', models.IntegerField(primary_key=True, serialize=False)),
                ('dataset', models.CharField(max_length=50)),
                ('organ', models.CharField(max_length=50)),
                ('original_image', models.FileField(upload_to='originalimage')),
                ('image', models.FileField(upload_to='image_one')),
                ('image_format', models.CharField(choices=[('MIRIAD', 'MIRIAD'), ('JPEG', 'JPEG'), ('J2K', 'J2K')], max_length=10)),
                ('alpha_value', models.FloatField(blank=True, null=True)),
                ('beta_value', models.FloatField(blank=True, null=True)),
                ('hauffman_coding', models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No')], max_length=12, null=True)),
                ('bit_depth', models.FloatField(blank=True, null=True)),
                ('quantizer_bit_depth', models.FloatField(blank=True, null=True)),
                ('compression_factor', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Testresult_Likter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=50)),
                ('modality', models.CharField(default='', max_length=50)),
                ('dataset', models.CharField(default='', max_length=50)),
                ('image_quid', models.IntegerField(default=0)),
                ('image', models.CharField(default='', max_length=50)),
                ('image_format', models.CharField(default='', max_length=50)),
                ('alpha_value', models.FloatField(blank=True, null=True)),
                ('beta_value', models.FloatField(blank=True, null=True)),
                ('hauffman_coding', models.CharField(blank=True, max_length=50, null=True)),
                ('bit_depth', models.FloatField(blank=True, null=True)),
                ('quantizer_bit_depth', models.FloatField(blank=True, null=True)),
                ('compression_factor', models.FloatField(blank=True, null=True)),
                ('original_image', models.CharField(default='', max_length=50)),
                ('score', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='UserProgress_Likter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('mr_progress', models.IntegerField(default=0)),
                ('ct_progress', models.IntegerField(default=0)),
                ('xr_progress', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='XR_Likter',
            fields=[
                ('q_id', models.IntegerField(primary_key=True, serialize=False)),
                ('dataset', models.CharField(max_length=50)),
                ('organ', models.CharField(max_length=50)),
                ('original_image', models.FileField(upload_to='originalimage')),
                ('image', models.FileField(upload_to='image_one')),
                ('image_format', models.CharField(choices=[('MIRIAD', 'MIRIAD'), ('JPEG', 'JPEG'), ('J2K', 'J2K')], max_length=10)),
                ('alpha_value', models.FloatField(blank=True, null=True)),
                ('beta_value', models.FloatField(blank=True, null=True)),
                ('hauffman_coding', models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No')], max_length=12, null=True)),
                ('bit_depth', models.FloatField(blank=True, null=True)),
                ('quantizer_bit_depth', models.FloatField(blank=True, null=True)),
                ('compression_factor', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
